# $ aws cloudformation create-stack --stack-name sampleapp --capabilities CAPABILITY_NAMED_IAM --template-body file://sampleapp-cloudformation.yaml
#
# IAM user should have these privileges to create, update or delete the sampleapp stack:
#
# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "cloudformation:CreateStack",
#                 "cloudformation:DeleteStack",
#                 "cloudformation:UpdateStack"
#             ],
#             "Resource": "arn:aws:cloudformation:<your-aws-region>:<your-aws-account-id>:stack/sampleapp/*"
#         },
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "cognito-idp:CreateUserPool"
#             ],
#             "Resource": "*"
#         },
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "cognito-idp:CreateUserPoolClient",
#                 "cognito-idp:CreateUserPoolDomain",
#                 "cognito-idp:DeleteUserPool",
#                 "cognito-idp:DeleteUserPoolClient",
#                 "cognito-idp:DeleteUserPoolDomain",
#                 "cognito-idp:ListTagsForResource",
#                 "cognito-idp:UpdateUserPool",
#                 "cognito-idp:UpdateUserPoolClient"
#             ],
#             "Resource": "arn:aws:cognito-idp:<your-aws-region>:<your-aws-account-id>:userpool/*"
#         },
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "cognito-identity:CreateIdentityPool",
#                 "cognito-identity:DeleteIdentityPool",
#                 "cognito-identity:SetIdentityPoolRoles",
#                 "cognito-identity:UpdateIdentityPool"
#             ],
#             "Resource": "arn:aws:cognito-identity:<your-aws-region>:<your-aws-account-id>:identitypool/*"
#         },
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "iam:CreateRole",
#                 "iam:DeleteRole",
#                 "iam:DeleteRolePolicy",
#                 "iam:GetRole",
#                 "iam:GetRolePolicy",
#                 "iam:PassRole",
#                 "iam:PutRolePolicy",
#                 "iam:UpdateAssumeRolePolicy"
#             ],
#             "Resource": [
#                 "arn:aws:iam::<your-aws-account-id>:role/Cognito_sampleappAuth_Role",
#                 "arn:aws:iam::<your-aws-account-id>:role/Cognito_sampleappUnauth_Role"
#             ]
#         }
#     ]
# }

Resources:

  SampleAppUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      AccountRecoverySetting: 
        RecoveryMechanisms: 
          - Name: verified_email
            Priority: 1
      AutoVerifiedAttributes: 
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: false
      Schema: 
        - Name: name
          Required: true
      UsernameAttributes:
        - email
      UsernameConfiguration: 
        CaseSensitive: false
      UserPoolName: sampleapp

  SampleAppUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain:
        !Sub
          - 'sampleapp-${RandomGUID}'
          - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      UserPoolId: !Ref SampleAppUserPool

  SampleAppUserPoolClientDev:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      AllowedOAuthFlows: 
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes: 
        - email
        - openid
        - profile
      CallbackURLs: 
        - http://localhost:5000/?auth-redirect
      ClientName: sampleapp-dev
      ExplicitAuthFlows: 
        - ALLOW_REFRESH_TOKEN_AUTH
      LogoutURLs: 
        - http://localhost:5000/?logoff-redirec
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders: 
        - COGNITO
      UserPoolId: !Ref SampleAppUserPool

  SampleAppUserPoolClientProd:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      AllowedOAuthFlows: 
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes: 
        - email
        - openid
        - profile
      CallbackURLs: 
        - https://my-github-account.github.io/sampleapp/?auth-redirect
      ClientName: sampleapp-dev
      ExplicitAuthFlows: 
        - ALLOW_REFRESH_TOKEN_AUTH
      LogoutURLs: 
        - https://my-github-account.github.io/sampleapp/?logoff-redirec
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders: 
        - COGNITO
      UserPoolId: !Ref SampleAppUserPool

  SampleAppIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowClassicFlow: false
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders: 
        - ClientId: !Ref SampleAppUserPoolClientDev
          ProviderName: !GetAtt SampleAppUserPool.ProviderName
          ServerSideTokenCheck: false
        - ClientId: !Ref SampleAppUserPoolClientProd
          ProviderName: !GetAtt SampleAppUserPool.ProviderName
          ServerSideTokenCheck: false
      IdentityPoolName: sampleapp

  SampleAppIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties: 
      IdentityPoolId: !Ref SampleAppIdentityPool
      Roles:
        "authenticated": !GetAtt SampleAppAuthRole.Arn
        "unauthenticated": !GetAtt SampleAppUnauthRole.Arn

  SampleAppAuthRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref SampleAppIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": "authenticated"
      Policies:
        - PolicyName: Cognito_sampleappAuth_Role_inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: '*'
      RoleName: Cognito_sampleappAuth_Role

  SampleAppUnauthRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref SampleAppIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": "unauthenticated"
      Policies:
        - PolicyName: Cognito_sampleappUnauth_Role_inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                Resource: '*'
      RoleName: Cognito_sampleappUnauth_Role


Outputs:

  UserPoolId:
    Value: !GetAtt SampleAppUserPool.ProviderName
    Export:
      Name: SAMPLE-APP-USER-POOL-ID

  UserPoolDomain:
    Value: !Ref SampleAppUserPoolDomain
    Export:
      Name: SAMPLE-APP-USER-POOL-DOMAIN

  UserPoolAppClientIdDev:
    Value: !Ref SampleAppUserPoolClientDev
    Export:
      Name: SAMPLE-APP-USER-POOL-APP-CLIENT-ID-DEV

  UserPoolAppClientIdProd:
    Value: !Ref SampleAppUserPoolClientProd
    Export:
      Name: SAMPLE-APP-USER-POOL-APP-CLIENT-ID-PROD

  IdentityPoolId:
    Value: !Ref SampleAppIdentityPool
    Export:
      Name: SAMPLE-APP-IDENTITY-POOL-ID
